const vehiculos = [     { id: 1, nombre: 'e-Bike Pro', cilindrada: '5cc', images: 'images/bici1.jpg', tipo: 'Bicicleta', precio: 2_299 },
                        { id: 2, nombre: 'Askoll', cilindrada: '50cc', images: 'images/motos1.jpg', tipo: 'Scooter', precio: 2_799 },
                        { id: 3, nombre: 'BMW  R1200', cilindrada: '1200cc', images: 'images/motos4.jpg', tipo: 'Motocicleta', precio: 1_399 },
                        { id: 4, nombre: 'kymco Superdink', cilindrada: '125cc', images: 'images/motos5.jpg', tipo: 'Scooter', precio: 1_399 },
                        { id: 5, nombre: 'Niu NGT', cilindrada: '50cc', images: 'images/motos6.jpg', tipo: 'Scooter', precio: 1_399 },
                        { id: 6, nombre: 'Peugeot Tweet', cilindrada: '125CC', images: 'images/motos8.jpg', tipo: 'Scooter', precio: 1_399 },
                        { id: 7, nombre: 'Peugeot Tweet Pro', cilindrada: '50cc', images: 'images/motos10.jpg', tipo: 'Scooter', precio: 1_399 },
                        { id: 8, nombre: 'Super Soco CPX', cilindrada: '125cc', images: 'images/motos11.jpg', tipo: 'Scooter', precio: 1_399 },
                        { id: 9, nombre: 'Sym JoyMax', cilindrada: '300cc', images: 'images/motos12.jpg', tipo: 'Scooter', precio: 1_399 },
                        { id: 10, nombre: 'Yamaha Tricity', cilindrada: '125cc', images: 'images/motos14.jpg', tipo: 'Tricuclo', precio: 1_399 },
                        { id: 11, nombre: 'Yamaha Xmax', cilindrada: '125cc', images: 'images/motos15.jpg', tipo: 'Scooter', precio: 1_399 },
                        { id: 12, nombre: 'Zero S Zf', cilindrada: '125cc', images: 'images/motos17.jpg', tipo: 'Motocicleta', precio: 1_399 },]